kit:
  name: "Oracle Weblogic Server"
  link: https://github.com/qubell-bazaar/component-oracle-weblogic 

  applications:
    - name: "WebLogic"
      manifest: https://raw.github.com/qubell-bazaar/component-oracle-weblogic/2.0-43p/component-oracle-weblogic.yml
  provider:
    name: "Tonomi"
    link: http://www.tonomi.com
  documentation:
    overview: |
      Pre-requisites:
        - AWS account
        - CentOS 6 x86_64
        - Oracle WebLogic installation files
